### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by fnyhy** [jason9693/MusicTransformer-tensorflow2.0#6]
When I run the generate.py ,the following error will happen.
Exception ignored in: <bound method _CheckpointRestoreCoordinator.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinator object at 0x7f30cc3c29e8>>
Traceback (most recent call last):
  File "/home/anaconda3/envs/musictransformer/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 240, in __del__
TypeError: 'NoneType' object is not callable

**Comment by jason9693** [comment]
Can you show me an error log in this repository, not in core package? 
I can't check an error point cause of this logs are only in core library.

**Comment by fnyhy** [comment]
python generate.py 2>error.log ,the error log is as followed.
2019-09-26 13:44:43.489796: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-09-26 13:44:44.884253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
2019-09-26 13:44:44.884581: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-26 13:44:44.887387: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-26 13:44:44.888597: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-09-26 13:44:44.888877: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-09-26 13:44:44.890685: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-09-26 13:44:44.891889: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-09-26 13:44:44.896214: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-09-26 13:44:44.898391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-26 13:44:44.898990: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-09-26 13:44:45.041753: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1be51334a0 executing computations on platform CUDA. Devices:
2019-09-26 13:44:45.041802: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2019-09-26 13:44:45.044782: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2100025000 Hz
2019-09-26 13:44:45.046064: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1be522a930 executing computations on platform Host. Devices:
2019-09-26 13:44:45.046089: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-26 13:44:45.047322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
2019-09-26 13:44:45.047373: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-26 13:44:45.047389: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-09-26 13:44:45.047402: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-09-26 13:44:45.047415: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-09-26 13:44:45.047428: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-09-26 13:44:45.047440: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-09-26 13:44:45.047454: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-09-26 13:44:45.049487: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-26 13:44:45.049528: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-09-26 13:44:45.051105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-26 13:44:45.051123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-09-26 13:44:45.051131: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-09-26 13:44:45.053911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11439 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-09-26 13:44:46.834182: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
Exception ignored in: <bound method _CheckpointRestoreCoordinator.__del__ of <tensorflow.python.training.tracking.util._CheckpointRestoreCoordinator object at 0x7ff6245c39e8>>
Traceback (most recent call last):
  File "/home/qixinhui/anaconda3/envs/musictransformer/lib/python3.6/site-packages/tensorflow/python/training/tracking/util.py", line 240, in __del__
TypeError: 'NoneType' object is not callable

**Comment by fnyhy** [comment]
And I found that I alwasy get the same result(the int sequence with the length and the same value) if I used the same 'inputs', no matter how I change the '--length'.

**Comment by jason9693** [comment]
@fnyhy  Did you set length value larger than 2048?
